### PR TITLE
Add Gatsby starter files

### PR DESCRIPTION
**Pull request by aaditkamat**
These files are generated using `gatsby-cli` with the [starter-default template.](https://github.com/gatsbyjs/gatsby-starter-default)

### CODE REVIEW

**Review by shreyasbapat — APPROVED** [review]
Looks good @aaditkamat . Thanks for the effort. 

cc @JeS24 @kakirastern

**Comment by kakirastern** [comment]
Looks good... Could do some global css styling with say the src/components/layout.css file, on top of using additional packages for the layout components like Material UI (https://material-ui.com/) and reactstrap (https://reactstrap.github.io/).

**Comment by aaditkamat** [comment]
Hi @kakirastern, I've been working upon it using [react-bootstrap](https://react-bootstrap.github.io/). I'll create a PR for adding the components in seperate PRs.

**Comment by kakirastern** [comment]
Yeah @aaditkamat That would be awesome! Appreciate your help for the org.

**Pull request merged**
